baseurl = "https://hugo-blog-7t2.pages.dev/"
languageCode = "zh-cn"
title = "Aurora的博客"

[params]
  mainSections = ["post"]
  rssFullContent = true
  favicon = "img/favicon.png"
  dateformat = "2006-01-02"

  [params.sidebar]
    emoji = "🔐"
    subtitle = "记录生活~"
    avatar = "img/avatar.png"

  [params.article]
    readingTime = true
    headingAnchor = false
    math = false

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

[params.widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } }
  ]
  page = [{ type = "toc" }]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 10
    params.icon = "book-open"
