baseurl = "https://hugo-papermod-alg.pages.dev/"
languageCode = "zh-cn"
title = "我的技术博客"
theme = "hugo-theme-stack"
# 不需要 config/_default 目录了，所有配置都在这个文件里

[params]
  mainSections = ["post"]
  rssFullContent = true
  favicon = "img/favicon.png"
  dateformat = "2006-01-02"

  [params.sidebar]
    emoji = "🔐"
    subtitle = "记录技术与思考"
    avatar = "img/avatar.png"

  [params.article]
    readingTime = true
    headingAnchor = false
    math = false

  [params.widgets.homepage]
    [{ type = "search" }, { type = "archives", params = { limit = 5 } }, { type = "categories", params = { limit = 10 } }, { type = "tag-cloud", params = { limit = 10 } }]

  [params.widgets.page]
    [{ type = "toc" }]

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 10
    params.icon = "book-open"
